# Generated by Django 4.1.7 on 2023-02-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0002_remove_assetinf_assetid_assetinf_assetname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assetinf',
            new_name='assetinfs',
        ),
    ]
