# Generated by Django 4.1.7 on 2023-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0003_rename_assetinf_assetinfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinfs',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assetinfs',
            name='assetname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assetinfs',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
