# Generated by Django 4.1.7 on 2023-02-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0004_assetinfs_location_alter_assetinfs_assetname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetinfs',
            old_name='id',
            new_name='ID',
        ),
    ]
