# Generated by Django 4.1.7 on 2023-02-21 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0005_rename_id_assetinfs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinfs',
            name='check_out_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check-out date'),
            preserve_default=False,
        ),
    ]
