# Generated by Django 4.1.7 on 2023-02-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0007_alter_assetinfs_assetname_alter_assetinfs_location_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetinfs',
            table='Asset',
        ),
    ]
