# Generated by Django 4.1.7 on 2023-02-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0009_rename_assetinfs_asset_alter_asset_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='asset',
            table=None,
        ),
    ]
