# Generated by Django 4.1.7 on 2023-02-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0010_check_out_alter_asset_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_out',
            name='asset',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='check_out',
            name='checkdate',
            field=models.DateTimeField(null=True),
        ),
    ]
