# Generated by Django 4.1.7 on 2023-02-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0012_check_out_assetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out',
            name='assetID',
            field=models.ForeignKey(default='1145141145142', on_delete=django.db.models.deletion.CASCADE, to='mainbody.asset'),
        ),
    ]
