# Generated by Django 4.1.7 on 2023-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0015_check_out_userid_alter_check_out_assetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.CharField(default='Available', max_length=100, null=True),
        ),
    ]
