# Generated by Django 4.1.7 on 2023-02-25 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0016_alter_asset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='check_out_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 15, 59, 16, 395249), verbose_name='check-out date'),
        ),
    ]
