# Generated by Django 4.1.7 on 2023-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0020_alter_asset_check_out_date_alter_check_out_checkdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out',
            name='asset',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='check_out',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
