# Generated by Django 4.1.7 on 2023-03-15 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainbody', '0021_alter_check_out_asset_alter_check_out_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('checkdate', models.DateTimeField()),
                ('assetID', models.ForeignKey(default='1145141145142', on_delete=django.db.models.deletion.CASCADE, to='mainbody.asset')),
                ('user', models.ForeignKey(default='Available', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='check_out',
        ),
    ]
