# Generated by Django 4.1.7 on 2023-03-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0022_checkout_delete_check_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='user',
            new_name='userID',
        ),
    ]
