# Generated by Django 4.1.7 on 2023-03-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0023_rename_user_checkout_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='asset',
        ),
    ]
